// Interfacetekst (NFE-006, V-11). Eigenaar: OFM-010 (schermen/wizard/*), OFM-025 (Maak zonder Claude).
// Alleen het eigenaarticket vult deze module. Keuzelabels komen uit `@shared/labels` (§9.1).
export const wizard = {
  titel: 'Nieuwe offerte',
  stappen: ['Klant', 'Het dak', "Extra's", 'Overig en maken'] as const,
  terugNaarOverzicht: 'Terug naar overzicht',
  vorige: 'Vorige',
  volgende: 'Volgende',
  maakDeOfferte: 'Maak de offerte',
  /** OFM-025 (FE-110, V-09): alleen zichtbaar als Claude niet werkt. */
  maakZonderClaude: 'Maak zonder Claude',
  laden: 'De offerte wordt geopend…',

  klant: {
    titel: 'Klant',
    privacy: 'Deze gegevens blijven op deze computer. Claude krijgt ze niet te zien.',
    aanhef: 'Aanhef',
    aanhefOpties: { dhr: 'Dhr.', mevr: 'Mevr.', fam: 'Fam.', bedrijf: 'Bedrijf' },
    naam: 'Naam',
    bedrijfsnaam: 'Bedrijfsnaam',
    straatHuisnummer: 'Straat en huisnummer',
    postcode: 'Postcode',
    plaats: 'Plaats',
    telefoon: 'Telefoon',
    email: 'E-mail',
    anderWerkadres: 'Het werk is op een ander adres',
    werkadres: 'Werkadres',
    naamLeeg: 'Vul de naam van de klant in',
    plaatsLeeg: 'Vul de plaats in',
    postcodeVorm: 'Deze postcode ziet er niet goed uit (bijvoorbeeld 5611 AB)',
    emailVorm: 'Dit e-mailadres ziet er niet goed uit',
  },

  dak: {
    titel: 'Het dak',
    soortWerk: 'Soort werk',
    soortDak: 'Soort dak',
    dakvlakken: 'Dakvlakken',
    dakvlakNaam: 'Naam van het dakvlak',
    maatwijze: 'Hoe wil je de maat invullen?',
    lxb: 'Lengte × breedte',
    m2: 'Direct m²',
    lengte: 'Lengte',
    breedte: 'Breedte',
    oppervlakte: 'Oppervlakte',
    meter: 'm',
    vierkanteMeter: 'm²',
    dakvlakToevoegen: 'Dakvlak toevoegen',
    dakvlakVerwijderen: (naam: string) => `${naam} verwijderen`,
    maxDakvlakken: 'Er kunnen maximaal 20 dakvlakken in één offerte.',
    totaal: 'Totaal',
    bedekking: 'Nieuwe dakbedekking',
    bedekkingAnders: 'Welke dakbedekking?',
    huidigeBedekking: 'Huidige dakbedekking',
    ondergrond: 'Ondergrond',
  },

  extras: {
    titel: "Extra's",
    slopen: 'Oude dakbedekking slopen en afvoeren',
    isolatie: 'Isolatie',
    isolatieMm: 'Dikte van de isolatie',
    mm: 'mm',
    // De namen van de keuzes (isolatie, extra's, afwerking, hoogte, garantie) staan sinds OFM-034 in de
    // database (Instellingen › Keuzelijsten); de startwaarden in src/shared/keuzelijsten.ts.
    strekkendeMeter: 'm¹',
    stuks: 'stuks',
    afwerking: 'Afwerking',
    hoogte: 'Hoogte',
    steiger: 'Steiger of hoogwerker nodig',
    garantie: 'Garantie',
    gewensteUitvoering: 'Gewenste uitvoering',
    gewensteUitvoeringHint: 'Bijvoorbeeld: voor de winter.',
  },

  overig: {
    titel: 'Overig en maken',
    overig: 'Overig',
    vraag: 'Wat moet er nog meer in de offerte? Schrijf het gewoon op.',
    hint: 'Zet hier geen namen, adressen of telefoonnummers in.',
    offertedatum: 'Offertedatum',
    geldigTot: (datum: string) => `Geldig tot ${datum}`,
    samenvatting: 'Samenvatting',
    ja: 'Ja',
    niets: 'Niets ingevuld',
  },

  /** Kopjes in de samenvatting van stap 4. */
  samenvatting: {
    klant: 'Klant',
    adres: 'Adres',
    werkadres: 'Werkadres',
    telefoon: 'Telefoon',
    email: 'E-mail',
    soortWerk: 'Soort werk',
    soortDak: 'Soort dak',
    dakvlakken: 'Dakvlakken',
    bedekking: 'Nieuwe dakbedekking',
    huidigeBedekking: 'Huidige dakbedekking',
    ondergrond: 'Ondergrond',
    slopen: 'Slopen en afvoeren',
    isolatie: 'Isolatie',
    afwerking: 'Afwerking',
    hoogte: 'Hoogte',
    steiger: 'Steiger of hoogwerker',
    garantie: 'Garantie',
    gewensteUitvoering: 'Gewenste uitvoering',
  },
};
